const form = document.getElementById('form')
const nameInput = document.getElementById('nome')
const ageInput = document.getElementById('idade')
const emailInput = document.getElementById('email')
const celInput = document.getElementById('cel')
const scholarityInput = document.getElementById('escolaridade')
const publiCheck = document.getElementById('check')
const interesseTextarea = document.getElementById('interesse')
